export const paths = {
  posts: () => '/',
  postDetail: (id: string, slug: string) => `/posts/${id}/${slug}`,
  postShareLinks: (id: string, slug: string) => `/posts/${id}/share-links?slug=${encodeURIComponent(slug)}`,
  postComments: (postId: string) => `/posts/${postId}/comments`,
  postCommentEdit: (postId: string, commentId: string) => `/posts/${postId}/comments/${commentId}`,
  postCommentDestroy: (postId: string, commentId: string) => `/posts/${postId}/comments/${commentId}/destroy`,
  myPosts: () => '/my-posts',
  myPostsNew: () => '/my-posts/new',
  myPostEdit: (id: string) => `/my-posts/${id}/edit`,
  myPostDestroy: (id: string) => `/my-posts/${id}/destroy`,
  myPostPublish: (id: string) => `/my-posts/${id}/publish`,
  myPostRetryPayment: (id: string) => `/my-posts/${id}/retry-payment`,
  paymentsSuccess: () => '/payments/success',
  paymentsCancel: () => '/payments/cancel',
  users: () => '/users',
  profile: () => '/profile',
  profileEdit: () => '/profile/edit',
  profileGeocode: () => '/profile/geocode',
  profileTransactionRefund: (id: string) => `/profile/transactions/${id}/refund`,
  analytics: () => '/analytics',
  uploadsPresign: () => '/uploads/presign',
  chat: () => '/chat',
  chatRoom: (id: string) => `/chat/${id}`,
  chatUsersSearch: () => '/chat/users/search',
  chatStartDm: () => '/chat/dm',
  chatV2: () => '/chat-v2',
  chatV2Room: (id: string) => `/chat-v2/${id}`,
  chatV2UsersSearch: () => '/chat-v2/users/search',
  chatV2StartDm: () => '/chat-v2/dm',
  login: (from?: string) => (from ? `/login?from=${encodeURIComponent(from)}` : '/login'),
  logout: () => '/logout',
  register: (from?: string) => (from ? `/register?from=${encodeURIComponent(from)}` : '/register'),
} as const;
